version: 2
jobs:
  build:
    working_directory: ~/redbot
    docker:
      - image: circleci/python:latest-browsers
    environment:
      MOZ_HEADLESS: 1
    steps:
      - checkout
      - run:
          name: install-requirements
          command: pip install --user mypy selenium thor markdown netaddr jinja2
      - run:
          name: test
          command: make -e
